### ISSUE TITLE
SOTO scroll item can't be added to a layout

### ISSUE THREAD

**Issue by n0proxy** [tentose/Gw2QuickItem#6]
The new xpac's hub teleport item [Wizard's Tower Teleportation Scroll] can't be added to a layout - it can't be found in the item list when I type its name into the 'find item' box. Not sure if the module needs an update to add new items to its list, or whether this is an API issue with automatically finding new items.

**Comment by tentose** [comment]
Issue resolved and should be available in latest release: https://github.com/tentose/Gw2QuickItem/releases/tag/0.1.0-6-main
